# Generated by Django 4.2.10 on 2024-03-25 20:24

import uuid

import django.db.models.deletion
from django.db import migrations, models
from django_add_default_value import AddDefaultValue, NOW


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        AddDefaultValue(
            model_name='UserChatLink',
            name='created_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='UserChatLink',
            name='updated_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='UserChatLink',
            name='active',
            value=True
        ),
    ]
