# Generated by Django 4.2.10 on 2024-03-25 20:31

import django.db.models.deletion
from django.db import migrations, models
from django_add_default_value import AddDefaultValue, NOW


class Migration(migrations.Migration):

    dependencies = [
        ('comet_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='O2OChatGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('group_id', models.UUIDField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_o2o_group', to='comet_chat.userchatlink')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_o2o_group', to='comet_chat.userchatlink')),
            ],
            options={
                'abstract': False,
            },
        ),
        AddDefaultValue(
            model_name='O2OChatGroup',
            name='created_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='O2OChatGroup',
            name='updated_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='O2OChatGroup',
            name='active',
            value=True
        ),
    ]
