# Generated by Django 4.2.10 on 2024-06-25 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django_add_default_value import AddDefaultValue, NOW

import users.models.user
from core_utils.database import UPDATE_TRIGGERS_SQL


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('auth0id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('blocked', models.BooleanField(default=False)),
            ],
            managers=[
                ('objects', users.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RoleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('role_name', models.CharField(max_length=70)),
                ('order', models.PositiveIntegerField()),
                ('can_assign', models.BooleanField(default=False)),
                ('can_remove', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('phone_verified', True)), fields=('phone_number',), name='user_verified_phone_number_uniq'),
        ),
        AddDefaultValue(
            model_name='Employee',
            name='created_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='Employee',
            name='updated_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='Employee',
            name='active',
            value=True
        ),
        AddDefaultValue(
            model_name='User',
            name='created_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='User',
            name='updated_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='User',
            name='active',
            value=True
        ),
        AddDefaultValue(
            model_name='User',
            name='blocked',
            value=False
        ),
        AddDefaultValue(
            model_name='User',
            name='phone_verified',
            value=False
        ),
        migrations.RunSQL(UPDATE_TRIGGERS_SQL),
    ]
