# Generated by Django 4.2.3 on 2023-07-16 19:24

from django.db import migrations, models

SQL = '''

    INSERT INTO "users_roleorder" (
          role_name, "order", can_assign, can_remove, created_date, updated_date
    )
    VALUES
    (
        'super_admin', 0, true, true, now(), now()
    );
     
    INSERT INTO "users_roleorder" (
          role_name, "order", can_assign, can_remove, created_date, updated_date
    )
    VALUES
    (
        'admin', 1, true, true, now(), now()
    );

    INSERT INTO "users_roleorder" (
          role_name, "order", can_assign, can_remove, created_date, updated_date
    )
    VALUES
    (
        'manager', 5, true, true, now(), now()
    );

    INSERT INTO "users_roleorder" (
          role_name, "order", can_assign, can_remove, created_date, updated_date
    )
    VALUES
    (
        'user', 99, false, false, now(), now()
    );
    '''


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('role_name', models.CharField(max_length=70)),
                ('order', models.PositiveIntegerField()),
                ('can_assign', models.BooleanField(default=False)),
                ('can_remove', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunSQL(SQL),
    ]
