# Generated by Django 4.2.3 on 2023-08-15 15:38
from django.core.serializers.json import DjangoJSONEncoder
from django.db import migrations, models
import django.db.models.deletion
from django_add_default_value import AddDefaultValue, NOW
import django.utils.timezone

from core_utils.database import UPDATE_TRIGGERS_SQL


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_rename_bucket_id_files_bucket_and_more'),
        ('users', '0003_rename_created_date_roleorder_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        AddDefaultValue(
            model_name='user',
            name='phone_verified',
            value=False
        ),

        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        AddDefaultValue(
            model_name='user',
            name='created_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='user',
            name='updated_at',
            value=NOW
        ),

        migrations.RunSQL(UPDATE_TRIGGERS_SQL),
    ]
