# Generated by Django 4.2.4 on 2023-08-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_name_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_verified', True)), fields=('phone_number',), name='user_verified_phone_number_uniq'),
        ),
    ]
