# Generated by Django 4.2.4 on 2023-08-17 13:43
from django.core.serializers.json import DjangoJSONEncoder
from django.db import migrations, models
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_user_verified_phone_number_uniq'),
    ]

    operations = [
    ]
