# Generated by Django 4.2.4 on 2023-08-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_rename_bucket_id_files_bucket_and_more'),
        ('users', '0006_alter_investordata_profile'),
    ]

    operations = [
    ]
