# Generated by Django 4.2.4 on 2023-08-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_investordata_accreditation_proof'),
    ]

    operations = [
    ]
