# Generated by Django 4.2.4 on 2023-08-25 11:20

from django.db import migrations

SQL = '''
    DELETE FROM "users_roleorder";  /* clear the table */

    INSERT INTO "users_roleorder" (
          role_name, "order", can_assign, can_remove, created_at, updated_at
    )
    VALUES
    (
        'admin', 0, true, true, now(), now()
    ),
    (
        'manager', 5, true, true, now(), now()
    ),
    (
        'user', 99, false, false, now(), now()
    );
'''


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_address_user_city_user_state_user_zip_code'),
    ]

    operations = [
        migrations.RunSQL(SQL)
    ]
