# Generated by Django 4.2.5 on 2023-09-25 10:22

from django.db import migrations, models
import django.db.models.deletion
from django_add_default_value import AddDefaultValue, NOW

from core_utils.database import UPDATE_TRIGGERS_SQL


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_update_role_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        AddDefaultValue(
            model_name='Employee',
            name='created_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='Employee',
            name='updated_at',
            value=NOW
        ),
        migrations.RunSQL(UPDATE_TRIGGERS_SQL),
    ]
