# Generated by Django 4.2.5 on 2023-09-26 15:09

from django.db import migrations, models
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True),
        ),
        AddDefaultValue(
            model_name='employee',
            name='active',
            value=True
        ),


        migrations.AddField(
            model_name='roleorder',
            name='active',
            field=models.BooleanField(default=True),
        ),
        AddDefaultValue(
            model_name='roleorder',
            name='active',
            value=True
        ),

        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        AddDefaultValue(
            model_name='user',
            name='active',
            value=True
        ),

    ]
