# Generated by Django 4.2.5 on 2023-09-26 15:24

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to='users.user'),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),

        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        AddDefaultValue(
            model_name='user',
            name='blocked',
            value=False
        ),

        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        AddDefaultValue(
            model_name='user',
            name='email_verified',
            value=False
        ),

    ]
