# Generated by Django 4.2.5 on 2023-09-27 10:49

from django.db import migrations, models
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_employee_id_alter_employee_email'),
    ]

    operations = [
    ]
