# Generated by Django 4.2.3 on 2023-08-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='bucket_id',
            new_name='bucket',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='uploaded_by_user_id',
            new_name='uploaded_by_user',
        ),
    ]
