# Generated by Django 4.2.1 on 2023-05-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('auth0id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True)),
                ('last_seen', models.DateTimeField(null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
