# Generated by Django 4.2.10 on 2024-06-25 23:15

import uuid

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django_add_default_value import AddDefaultValue, NOW

import core_utils.utils
from core_utils.database import UPDATE_TRIGGERS_SQL


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaidInternal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('param_name', models.CharField(primary_key=True, serialize=False)),
                ('value_num', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('value_str', models.CharField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        AddDefaultValue(
            model_name='PlaidInternal',
            name='created_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='PlaidInternal',
            name='updated_at',
            value=NOW
        ),
        migrations.CreateModel(
            name='PlaidLinkStatus',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaidTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('authorization_body', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('transfer_body', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('transfer_status', models.CharField()),
                ('transfer_type', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaidTransferEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('event_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('event_body', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('event_type', models.CharField(max_length=100)),
                ('event_timestamp', models.DateTimeField()),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plaid_app.plaidtransfer')),
            ],
            options={
                'abstract': False,
            },
        ),
        AddDefaultValue(
            model_name='PlaidTransferEvent',
            name='active',
            value=True
        ),
        AddDefaultValue(
            model_name='PlaidTransferEvent',
            name='created_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='PlaidTransferEvent',
            name='updated_at',
            value=NOW
        ),
        migrations.CreateModel(
            name='PlaidLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=False)),
                ('plaid_user_id', models.UUIDField(default=uuid.uuid4)),
                ('permanent_token', models.TextField(null=True)),
                ('item_id', models.TextField(null=True, unique=True)),
                ('institution_meta_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('account_meta_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('item_status_fk', core_utils.utils.AttrForeignKey(db_column='item_status', default='normal', id_attname='item_status', on_delete=django.db.models.deletion.PROTECT, to='plaid_app.plaidlinkstatus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        AddDefaultValue(
            model_name='PlaidLink',
            name='created_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='PlaidLink',
            name='updated_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='PlaidLink',
            name='active',
            value=False
        ),
        AddDefaultValue(
            model_name='PlaidLink',
            name='item_status',
            value='normal'
        ),
        AddDefaultValue(
            model_name='PlaidLink',
            name='account_meta_data',
            value='{}'
        ),
        AddDefaultValue(
            model_name='PlaidLink',
            name='institution_meta_data',
            value='{}'
        ),
        migrations.RunSQL(UPDATE_TRIGGERS_SQL),
    ]
