# Generated by Django 4.2.3 on 2023-08-15 15:38

from django.db import migrations, models
import django.db.models.deletion
import uuid

from django_add_default_value import AddDefaultValue, NOW

from core_utils.database import UPDATE_TRIGGERS_SQL

SQL = '''
    ALTER TABLE "plaid_app_plaidlink" ALTER COLUMN "plaid_user_id" SET DEFAULT public.gen_random_uuid();

'''

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_rename_created_date_roleorder_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaidLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=False)),
                ('plaid_user_id', models.UUIDField(default=uuid.uuid4)),
                ('permanent_token', models.TextField(null=True)),
                ('item_id', models.TextField(null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        AddDefaultValue(
            model_name='PlaidLink',
            name='created_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='PlaidLink',
            name='updated_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='PlaidLink',
            name='active',
            value=False
        ),
        migrations.RunSQL(UPDATE_TRIGGERS_SQL),

    ]
