# Generated by Django 4.2.5 on 2023-09-11 20:09
from django.core.serializers.json import DjangoJSONEncoder
from django.db import migrations, models
import django.db.models.deletion
from django_add_default_value import AddDefaultValue, NOW

from core_utils.database import UPDATE_TRIGGERS_SQL


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_user_verified_phone_number_uniq'),
        ('plaid_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaidInternal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('param_name', models.CharField(primary_key=True, serialize=False)),
                ('value_num', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('value_str', models.CharField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        AddDefaultValue(
            model_name='PlaidInternal',
            name='created_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='PlaidInternal',
            name='updated_at',
            value=NOW
        ),
        migrations.CreateModel(
            name='PlaidTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('authorization_body', models.JSONField(encoder=DjangoJSONEncoder)),
                ('transfer_body', models.JSONField(encoder=DjangoJSONEncoder)),
                ('transfer_status', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        AddDefaultValue(
            model_name='PlaidTransfer',
            name='created_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='PlaidTransfer',
            name='updated_at',
            value=NOW
        ),
        migrations.CreateModel(
            name='PlaidTransferEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('event_body', models.JSONField(encoder=DjangoJSONEncoder)),
                ('event_type', models.CharField(max_length=100)),
                ('event_timestamp', models.DateTimeField()),
                ('transfer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='plaid_app.plaidtransfer')),
            ],
            options={
                'abstract': False,
            },
        ),
        AddDefaultValue(
            model_name='PlaidTransferEvent',
            name='created_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='PlaidTransferEvent',
            name='updated_at',
            value=NOW
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('transfer_in_progress', 'transfer_in_progress'), ('transfer_complete', 'transfer_complete'), ('transfer_failed', 'transfer_failed')], default='pending', max_length=20)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transaction_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='plaid_app.plaidtransfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
        ),
        AddDefaultValue(
            model_name='Investment',
            name='created_at',
            value=NOW
        ),
        AddDefaultValue(
            model_name='Investment',
            name='updated_at',
            value=NOW
        ),
        migrations.RunSQL(UPDATE_TRIGGERS_SQL),

    ]
