# Generated by Django 4.2.5 on 2023-09-13 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_app', '0002_plaidinternal_plaidtransfer_plaidtransferevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaidtransferevent',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plaid_app.plaidtransfer'),
        ),
    ]
