# Generated by Django 4.2.5 on 2023-09-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_app', '0003_alter_plaidtransferevent_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaidtransfer',
            name='transfer_type',
            field=models.CharField(default='unknown'),
            preserve_default=False,
        ),
    ]
