# Generated by Django 4.2.5 on 2023-09-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_app', '0004_plaidtransfer_transfer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('transfer_rejected', 'transfer_rejected'), ('transfer_in_progress', 'transfer_in_progress'), ('transfer_complete', 'transfer_complete'), ('transfer_failed', 'transfer_failed'), ('transfer_returned', 'transfer_returned'), ('transfer_canceled', 'transfer_canceled')], default='pending', max_length=20),
        ),
    ]
