# Generated by Django 4.2.5 on 2023-09-26 15:09

from django.db import migrations, models
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_app', '0005_alter_investment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaidinternal',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plaidtransferevent',
            name='active',
            field=models.BooleanField(default=True),
        ),
        AddDefaultValue(
            model_name='plaidinternal',
            name='active',
            value=True
        ),
        AddDefaultValue(
            model_name='plaidtransferevent',
            name='active',
            value=True
        ),

    ]
