# Generated by Django 4.2.10 on 2024-06-25 23:15

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name_on_account', models.CharField(max_length=100)),
                ('ach', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ACHTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('direction', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], max_length=10)),
                ('effective_date', models.DateTimeField()),
                ('error', models.CharField(max_length=10, null=True)),
                ('sec_code', models.CharField(choices=[('ccd', 'ccd'), ('cie', 'cie'), ('ppd', 'ppd'), ('tel', 'tel'), ('web', 'web')], max_length=3)),
                ('service', models.CharField(choices=[('standard', 'standard'), ('sameday', 'sameday')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('canceled', 'canceled'), ('error', 'error'), ('sent', 'sent'), ('returned', 'returned')], max_length=10)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasuryprime_app.counterpartylink')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='counterpartylink',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user',), name='unique_counterpartylink_user'),
        ),
    ]
