name: "Backend Dev Deploy"

on:
  push:
    branches: [ dev ]
    paths:
      - 'backend/**/*'
      - '.github/**/*'
  workflow_dispatch:

jobs:
  build-backend-dev:
    uses: ./.github/workflows/backend-deploy.yml
    with:
      aws_region: us-west-1

      ecr_repo_hasura: sfa/hasura-dev
      ecr_repo_django: sfa/django-app-dev

      ecs_cluster: sfa-dev-Cluster

      gql_service: sfa-dev-hasura
      gql_task_def: sfa-dev-HasuraTaskDefinition

      django_service: sfa-dev-djangoApi
      django_task_def: sfa-dev-DjangoTaskDefinition
      django_drq_service: sfa-dev-djangoDMTQ
      django_drq_task_def: sfa-dev-DjangoDMTQTaskDefinition

    secrets: inherit
