name: frontend
on:
  push:
    branches: [ master ]
    paths:
      - 'frontend/**/*'
jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Enable corepack
        run: corepack enable

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Build frontend
        working-directory: ./frontend
        run: |
          pnpm install --prefer-offline --frozen-lockfile
          pnpm build

      - name: Deploy frontend
        working-directory: ./frontend
        run: |
          pnpm install s3-spa-upload@^2.1.5
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-west-1
          pnpm exec s3-spa-upload ./dist react-cors-spa-sfa-test27 -d

