name: "Deploy Frontend"
on:
  workflow_call:
    inputs:
      environment:
        description: "deploy environment, e.g. dev, staging or production"
        type: string
      deploy_target:
        description: "Target to deploy to"
        required: true
        type: string
      app_title:
        description: "application title"
        default: "SFA APP"
        type: string
      sentry_dsn:
        description: "Sentry dns"
        type: string
      hasura_gql:
        description: "hasura GQL endpoint url"
        type: string
      auth0_domain:
        description: "auth0 app domain"
        type: string
      auth0_client_id:
        description: "auth0 app client ID"
        type: string
      auth0_audience:
        description: "auth0 api audience"
        type: string
      heap_id:
        description: "heap analytics id"
        type: string

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Enable corepack
        run: corepack enable

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Build frontend
        working-directory: ./frontend
        run: |
          pnpm install --prefer-offline --frozen-lockfile
          pnpm build
        env:
          VITE_APP_TITLE: ${{ inputs.app_title }}
          VITE_APP_ENVIRONMENT: ${{ inputs.environment }}
          VITE_APP_SENTRY_DSN: ${{ inputs.sentry_dsn }}
          VITE_APP_HASURA_HTTP_URI: ${{ inputs.hasura_gql }}
          VITE_APP_AUTH0_DOMAIN: ${{ inputs.auth0_domain }}
          VITE_APP_AUTH0_CLIENT_ID: ${{ inputs.auth0_client_id }}
          VITE_APP_AUTH0_AUDIENCE: ${{ inputs.auth0_audience }}
          VITE_APP_HEAP_ID: ${{inputs.heap_id}}

      - name: Deploy frontend
        working-directory: ./frontend
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-west-1
          pnpm dlx s3-spa-upload ./dist ${{ inputs.deploy_target }} -d
